# PRODUCTION dockerfile.

FROM node:12.13.0 as build

ARG AZURE_REGISTRY_USERNAME
ARG AZURE_REGISTRY_PASSWORD

RUN apt-get update

RUN mkdir -p /app
WORKDIR /app

COPY --chown=node .npmrc.example ./.npmrc
COPY --chown=node package*.json ./

ADD ./ /app

RUN npm install

RUN npm run docs:prod:build

FROM nginx:1.17
COPY --from=build /app/storybook-static /usr/share/nginx/html
COPY ./scripts/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
