# PRODUCTION dockerfile.

FROM node:12.13.0 as build

ARG AZURE_REGISTRY_USERNAME
ARG AZURE_REGISTRY_PASSWORD

RUN apt-get update

RUN mkdir -p /app
WORKDIR /app

ADD ./ /app

RUN sh ./scripts/writeAzureRegistry.sh
RUN npm install

RUN npm run docs:prod:build

FROM nginx:1.17
COPY --from=build /app/styleguide /usr/share/nginx/html
COPY ./scripts/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
